export const tools = {
  frontend: [
    "React",
    "Nextjs",
    "SASS",
    "Typescript",
    "Jest",
    "Angular",
    "Firebase",
    "TailwindCSS",
  ],
  backend: [
    "Java",
    "Spring Framework",
    "PostgreSQL",
    "Junit",
    "Lua",
    "Kotlin",
    "Nest.js",
    "OracleDB",
  ],
  mobile: ["Android Studio", "React Native", "PWA", "Kotlin"],
  cloud: [
    "AWS",
    "Azure",
    "Jenkins",
    "Github Actions",
    "Docker",
    "CI/CD",
    "Kubernets",
  ],
};
