name: Deploy to Firebase Hosting on PR
run-name: Deploy to firebase

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Checkout
        uses: actions/checkout@v4

      - run: bun install && bun run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_15896 }}"
          projectId: portfolio-15896
          channelId: live
